#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 134
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  sym_text_node = 1,
  sym_tag_name = 2,
  anon_sym_LT = 3,
  anon_sym_GT = 4,
  anon_sym_LT_SLASH = 5,
  anon_sym_SLASH_GT = 6,
  sym_attribute_name = 7,
  anon_sym_EQ = 8,
  anon_sym_SQUOTE = 9,
  anon_sym_DQUOTE = 10,
  sym__mustache_safe_single_quote_string_literal_content = 11,
  sym__mustache_safe_double_quote_string_literal_content = 12,
  anon_sym_as = 13,
  anon_sym_PIPE = 14,
  sym__mustache_statement_start = 15,
  sym__mustache_statement_end = 16,
  anon_sym_DOT = 17,
  sym_identifier = 18,
  sym_helper_identifier = 19,
  anon_sym_LPAREN = 20,
  anon_sym_RPAREN = 21,
  anon_sym_POUND = 22,
  anon_sym_SLASH = 23,
  aux_sym__single_quote_string_literal_token1 = 24,
  aux_sym__double_quote_string_literal_token1 = 25,
  sym_number_literal = 26,
  anon_sym_true = 27,
  anon_sym_false = 28,
  sym_comment = 29,
  sym_template = 30,
  sym__declaration = 31,
  sym_element_node_start = 32,
  sym_element_node_end = 33,
  sym_element_node_void = 34,
  sym_element_node = 35,
  sym_attribute_node = 36,
  sym_concat_statement = 37,
  sym__single_quote_concat_statement = 38,
  sym__double_quote_concat_statement = 39,
  sym_block_params = 40,
  sym_path_expression = 41,
  sym__identifier = 42,
  sym__value = 43,
  sym_mustache_statement = 44,
  sym_sub_expression = 45,
  sym_block_statement_start = 46,
  sym_block_statement_end = 47,
  sym_block_statement = 48,
  sym_string_literal = 49,
  sym__single_quote_string_literal = 50,
  sym__double_quote_string_literal = 51,
  sym_boolean_literal = 52,
  aux_sym_template_repeat1 = 53,
  aux_sym_element_node_start_repeat1 = 54,
  aux_sym__single_quote_concat_statement_repeat1 = 55,
  aux_sym__double_quote_concat_statement_repeat1 = 56,
  aux_sym_block_params_repeat1 = 57,
  aux_sym_mustache_statement_repeat1 = 58,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text_node] = "text_node",
  [sym_tag_name] = "tag_name",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_EQ] = "=",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym__mustache_safe_single_quote_string_literal_content] = "_mustache_safe_single_quote_string_literal_content",
  [sym__mustache_safe_double_quote_string_literal_content] = "_mustache_safe_double_quote_string_literal_content",
  [anon_sym_as] = "as",
  [anon_sym_PIPE] = "|",
  [sym__mustache_statement_start] = "_mustache_statement_start",
  [sym__mustache_statement_end] = "_mustache_statement_end",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [sym_helper_identifier] = "helper_identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_POUND] = "#",
  [anon_sym_SLASH] = "/",
  [aux_sym__single_quote_string_literal_token1] = "_single_quote_string_literal_token1",
  [aux_sym__double_quote_string_literal_token1] = "_double_quote_string_literal_token1",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_comment] = "comment_statement",
  [sym_template] = "template",
  [sym__declaration] = "_declaration",
  [sym_element_node_start] = "element_node_start",
  [sym_element_node_end] = "element_node_end",
  [sym_element_node_void] = "element_node_void",
  [sym_element_node] = "element_node",
  [sym_attribute_node] = "attribute_node",
  [sym_concat_statement] = "concat_statement",
  [sym__single_quote_concat_statement] = "_single_quote_concat_statement",
  [sym__double_quote_concat_statement] = "_double_quote_concat_statement",
  [sym_block_params] = "block_params",
  [sym_path_expression] = "path_expression",
  [sym__identifier] = "_identifier",
  [sym__value] = "_value",
  [sym_mustache_statement] = "mustache_statement",
  [sym_sub_expression] = "sub_expression",
  [sym_block_statement_start] = "block_statement_start",
  [sym_block_statement_end] = "block_statement_end",
  [sym_block_statement] = "block_statement",
  [sym_string_literal] = "string_literal",
  [sym__single_quote_string_literal] = "_single_quote_string_literal",
  [sym__double_quote_string_literal] = "_double_quote_string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_element_node_start_repeat1] = "element_node_start_repeat1",
  [aux_sym__single_quote_concat_statement_repeat1] = "_single_quote_concat_statement_repeat1",
  [aux_sym__double_quote_concat_statement_repeat1] = "_double_quote_concat_statement_repeat1",
  [aux_sym_block_params_repeat1] = "block_params_repeat1",
  [aux_sym_mustache_statement_repeat1] = "mustache_statement_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text_node] = sym_text_node,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__mustache_safe_single_quote_string_literal_content] = sym__mustache_safe_single_quote_string_literal_content,
  [sym__mustache_safe_double_quote_string_literal_content] = sym__mustache_safe_double_quote_string_literal_content,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym__mustache_statement_start] = sym__mustache_statement_start,
  [sym__mustache_statement_end] = sym__mustache_statement_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [sym_helper_identifier] = sym_helper_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [aux_sym__single_quote_string_literal_token1] = aux_sym__single_quote_string_literal_token1,
  [aux_sym__double_quote_string_literal_token1] = aux_sym__double_quote_string_literal_token1,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_comment] = sym_comment,
  [sym_template] = sym_template,
  [sym__declaration] = sym__declaration,
  [sym_element_node_start] = sym_element_node_start,
  [sym_element_node_end] = sym_element_node_end,
  [sym_element_node_void] = sym_element_node_void,
  [sym_element_node] = sym_element_node,
  [sym_attribute_node] = sym_attribute_node,
  [sym_concat_statement] = sym_concat_statement,
  [sym__single_quote_concat_statement] = sym__single_quote_concat_statement,
  [sym__double_quote_concat_statement] = sym__double_quote_concat_statement,
  [sym_block_params] = sym_block_params,
  [sym_path_expression] = sym_path_expression,
  [sym__identifier] = sym__identifier,
  [sym__value] = sym__value,
  [sym_mustache_statement] = sym_mustache_statement,
  [sym_sub_expression] = sym_sub_expression,
  [sym_block_statement_start] = sym_block_statement_start,
  [sym_block_statement_end] = sym_block_statement_end,
  [sym_block_statement] = sym_block_statement,
  [sym_string_literal] = sym_string_literal,
  [sym__single_quote_string_literal] = sym__single_quote_string_literal,
  [sym__double_quote_string_literal] = sym__double_quote_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_element_node_start_repeat1] = aux_sym_element_node_start_repeat1,
  [aux_sym__single_quote_concat_statement_repeat1] = aux_sym__single_quote_concat_statement_repeat1,
  [aux_sym__double_quote_concat_statement_repeat1] = aux_sym__double_quote_concat_statement_repeat1,
  [aux_sym_block_params_repeat1] = aux_sym_block_params_repeat1,
  [aux_sym_mustache_statement_repeat1] = aux_sym_mustache_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text_node] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__mustache_safe_single_quote_string_literal_content] = {
    .visible = false,
    .named = true,
  },
  [sym__mustache_safe_double_quote_string_literal_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym__mustache_statement_start] = {
    .visible = false,
    .named = true,
  },
  [sym__mustache_statement_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_helper_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__single_quote_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__double_quote_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_element_node_start] = {
    .visible = true,
    .named = true,
  },
  [sym_element_node_end] = {
    .visible = true,
    .named = true,
  },
  [sym_element_node_void] = {
    .visible = true,
    .named = true,
  },
  [sym_element_node] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_node] = {
    .visible = true,
    .named = true,
  },
  [sym_concat_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quote_concat_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__double_quote_concat_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_block_params] = {
    .visible = true,
    .named = true,
  },
  [sym_path_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_mustache_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_sub_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement_start] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement_end] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quote_string_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__double_quote_string_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_node_start_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__single_quote_concat_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__double_quote_concat_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mustache_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_path = 1,
  field_program = 2,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_path] = "path",
  [field_program] = "program",
};

static const TSFieldMapSlice ts_field_map_slices[3] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_program, 1},
  [1] =
    {field_path, 2},
};

static TSSymbol ts_alias_sequences[3][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static inline bool sym_attribute_name_character_set_1(int32_t lookahead) {
  return
    lookahead == 0 ||
    lookahead == '\t' ||
    lookahead == '\n' ||
    lookahead == '\r' ||
    lookahead == ' ' ||
    lookahead == '"' ||
    lookahead == '\'' ||
    lookahead == '/' ||
    ('<' <= lookahead && lookahead <= '>') ||
    lookahead == '{' ||
    lookahead == '}';
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '#') ADVANCE(53);
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == ')') ADVANCE(52);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead == 'a') ADVANCE(41);
      if (lookahead == 'f') ADVANCE(39);
      if (lookahead == 't') ADVANCE(45);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '|') ADVANCE(35);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('b' <= lookahead && lookahead <= 'e')) ADVANCE(42);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '#') ADVANCE(53);
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead == '(') ADVANCE(51);
      if (lookahead == ')') ADVANCE(52);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(54);
      if (lookahead == 'f') ADVANCE(39);
      if (lookahead == 't') ADVANCE(45);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'e')) ADVANCE(42);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(30);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '|') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<' &&
          lookahead != '}') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == '{') ADVANCE(36);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(37);
      END_STATE();
    case 10:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(59);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(57);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 14:
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14)
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '{') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_text_node);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text_node);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 's') ADVANCE(34);
      if (!sym_attribute_name_character_set_1(lookahead)) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_attribute_name);
      if (!sym_attribute_name_character_set_1(lookahead)) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__mustache_safe_single_quote_string_literal_content);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__mustache_safe_single_quote_string_literal_content);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__mustache_safe_double_quote_string_literal_content);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__mustache_safe_double_quote_string_literal_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_as);
      if (lookahead == '-') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_as);
      if (!sym_attribute_name_character_set_1(lookahead)) ADVANCE(25);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__mustache_statement_start);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__mustache_statement_end);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == 'a') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('b' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == 's') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == '_') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == 'e') ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == 'e') ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == 'r') ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == 's') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead == 'u') ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_helper_identifier);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym__single_quote_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym__single_quote_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym__double_quote_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__double_quote_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '_') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 15, .external_lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 15, .external_lex_state = 1},
  [23] = {.lex_state = 15, .external_lex_state = 1},
  [24] = {.lex_state = 15, .external_lex_state = 1},
  [25] = {.lex_state = 15, .external_lex_state = 1},
  [26] = {.lex_state = 15, .external_lex_state = 1},
  [27] = {.lex_state = 15, .external_lex_state = 1},
  [28] = {.lex_state = 15, .external_lex_state = 1},
  [29] = {.lex_state = 15, .external_lex_state = 1},
  [30] = {.lex_state = 15, .external_lex_state = 1},
  [31] = {.lex_state = 15, .external_lex_state = 1},
  [32] = {.lex_state = 15, .external_lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 6, .external_lex_state = 1},
  [42] = {.lex_state = 6, .external_lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 6, .external_lex_state = 1},
  [52] = {.lex_state = 6, .external_lex_state = 1},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 6, .external_lex_state = 1},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 15, .external_lex_state = 1},
  [59] = {.lex_state = 6, .external_lex_state = 1},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 6, .external_lex_state = 1},
  [63] = {.lex_state = 6, .external_lex_state = 1},
  [64] = {.lex_state = 15, .external_lex_state = 1},
  [65] = {.lex_state = 6, .external_lex_state = 1},
  [66] = {.lex_state = 15, .external_lex_state = 1},
  [67] = {.lex_state = 15, .external_lex_state = 1},
  [68] = {.lex_state = 15, .external_lex_state = 1},
  [69] = {.lex_state = 6, .external_lex_state = 1},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 15, .external_lex_state = 1},
  [74] = {.lex_state = 6, .external_lex_state = 1},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 15, .external_lex_state = 1},
  [77] = {.lex_state = 6, .external_lex_state = 1},
  [78] = {.lex_state = 15, .external_lex_state = 1},
  [79] = {.lex_state = 15, .external_lex_state = 1},
  [80] = {.lex_state = 15, .external_lex_state = 1},
  [81] = {.lex_state = 15, .external_lex_state = 1},
  [82] = {.lex_state = 15, .external_lex_state = 1},
  [83] = {.lex_state = 15, .external_lex_state = 1},
  [84] = {.lex_state = 15, .external_lex_state = 1},
  [85] = {.lex_state = 15, .external_lex_state = 1},
  [86] = {.lex_state = 15, .external_lex_state = 1},
  [87] = {.lex_state = 15, .external_lex_state = 1},
  [88] = {.lex_state = 15, .external_lex_state = 1},
  [89] = {.lex_state = 15, .external_lex_state = 1},
  [90] = {.lex_state = 15, .external_lex_state = 1},
  [91] = {.lex_state = 15, .external_lex_state = 1},
  [92] = {.lex_state = 15, .external_lex_state = 1},
  [93] = {.lex_state = 6, .external_lex_state = 1},
  [94] = {.lex_state = 15, .external_lex_state = 1},
  [95] = {.lex_state = 15, .external_lex_state = 1},
  [96] = {.lex_state = 15, .external_lex_state = 1},
  [97] = {.lex_state = 5},
  [98] = {.lex_state = 15, .external_lex_state = 1},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 5},
  [101] = {.lex_state = 5},
  [102] = {.lex_state = 5},
  [103] = {.lex_state = 5},
  [104] = {.lex_state = 4},
  [105] = {.lex_state = 4},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 14},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 10},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 14},
  [125] = {.lex_state = 10},
  [126] = {.lex_state = 11},
  [127] = {.lex_state = 12},
  [128] = {.lex_state = 14},
  [129] = {.lex_state = 12},
  [130] = {.lex_state = 11},
  [131] = {.lex_state = 14},
  [132] = {.lex_state = 10},
  [133] = {.lex_state = 0},
};

enum {
  ts_external_token_comment = 0,
};

static TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_comment] = sym_comment,
};

static bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_comment] = true,
  },
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym__mustache_statement_start] = ACTIONS(1),
    [sym__mustache_statement_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_helper_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(133),
    [sym__declaration] = STATE(32),
    [sym_element_node_start] = STATE(22),
    [sym_element_node_void] = STATE(73),
    [sym_element_node] = STATE(32),
    [sym_mustache_statement] = STATE(32),
    [sym_block_statement_start] = STATE(31),
    [sym_block_statement] = STATE(32),
    [aux_sym_template_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_text_node] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [sym__mustache_statement_start] = ACTIONS(9),
    [sym_comment] = ACTIONS(5),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      sym__mustache_statement_end,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      anon_sym_SLASH,
    ACTIONS(25), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(20), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [45] = 12,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      sym__mustache_statement_end,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      sym_number_literal,
    ACTIONS(29), 1,
      anon_sym_SLASH,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(20), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [90] = 12,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_as,
    ACTIONS(37), 1,
      sym__mustache_statement_end,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_number_literal,
    STATE(33), 1,
      sym__identifier,
    STATE(115), 1,
      sym_block_params,
    ACTIONS(39), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(45), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(44), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(9), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [135] = 12,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_as,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym__mustache_statement_end,
    ACTIONS(49), 1,
      sym_number_literal,
    STATE(33), 1,
      sym__identifier,
    STATE(122), 1,
      sym_block_params,
    ACTIONS(39), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(45), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(44), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(4), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [180] = 11,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(51), 1,
      sym__mustache_statement_end,
    ACTIONS(53), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(18), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [222] = 11,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      sym__mustache_statement_end,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(20), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [264] = 10,
    ACTIONS(55), 1,
      anon_sym_SQUOTE,
    ACTIONS(58), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(61), 2,
      sym__mustache_statement_end,
      anon_sym_RPAREN,
    ACTIONS(63), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(72), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(8), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [304] = 11,
    ACTIONS(61), 1,
      sym__mustache_statement_end,
    ACTIONS(75), 1,
      anon_sym_SQUOTE,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      anon_sym_as,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_number_literal,
    STATE(33), 1,
      sym__identifier,
    ACTIONS(83), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(92), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(44), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(9), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [346] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(97), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(19), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [385] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(99), 1,
      sym__mustache_statement_end,
    ACTIONS(101), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(12), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [424] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      sym__mustache_statement_end,
    ACTIONS(105), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(8), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [463] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      sym__mustache_statement_end,
    ACTIONS(109), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(16), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [502] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(113), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(17), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [541] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      sym_number_literal,
    ACTIONS(115), 1,
      sym__mustache_statement_end,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(8), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [580] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      sym_number_literal,
    ACTIONS(117), 1,
      sym__mustache_statement_end,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(8), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [619] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      sym_number_literal,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(8), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [658] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      sym_number_literal,
    ACTIONS(121), 1,
      sym__mustache_statement_end,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(8), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [697] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      sym_number_literal,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(8), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [736] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      sym_number_literal,
    ACTIONS(125), 1,
      sym__mustache_statement_end,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(8), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [775] = 10,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      sym__mustache_statement_end,
    ACTIONS(129), 1,
      sym_number_literal,
    STATE(34), 1,
      sym__identifier,
    ACTIONS(17), 2,
      sym_identifier,
      sym_helper_identifier,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 2,
      sym__single_quote_string_literal,
      sym__double_quote_string_literal,
    STATE(15), 6,
      sym_path_expression,
      sym__value,
      sym_sub_expression,
      sym_string_literal,
      sym_boolean_literal,
      aux_sym_mustache_statement_repeat1,
  [814] = 9,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(135), 1,
      anon_sym_LT_SLASH,
    ACTIONS(137), 1,
      sym__mustache_statement_start,
    STATE(23), 1,
      sym_element_node_start,
    STATE(29), 1,
      sym_block_statement_start,
    STATE(76), 1,
      sym_element_node_end,
    STATE(85), 1,
      sym_element_node_void,
    ACTIONS(131), 2,
      sym_comment,
      sym_text_node,
    STATE(24), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [847] = 9,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(137), 1,
      sym__mustache_statement_start,
    ACTIONS(141), 1,
      anon_sym_LT_SLASH,
    STATE(23), 1,
      sym_element_node_start,
    STATE(29), 1,
      sym_block_statement_start,
    STATE(83), 1,
      sym_element_node_end,
    STATE(85), 1,
      sym_element_node_void,
    ACTIONS(139), 2,
      sym_comment,
      sym_text_node,
    STATE(25), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [880] = 9,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(135), 1,
      anon_sym_LT_SLASH,
    ACTIONS(137), 1,
      sym__mustache_statement_start,
    STATE(23), 1,
      sym_element_node_start,
    STATE(29), 1,
      sym_block_statement_start,
    STATE(81), 1,
      sym_element_node_end,
    STATE(85), 1,
      sym_element_node_void,
    ACTIONS(143), 2,
      sym_comment,
      sym_text_node,
    STATE(30), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [913] = 9,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(137), 1,
      sym__mustache_statement_start,
    ACTIONS(141), 1,
      anon_sym_LT_SLASH,
    STATE(23), 1,
      sym_element_node_start,
    STATE(29), 1,
      sym_block_statement_start,
    STATE(85), 1,
      sym_element_node_void,
    STATE(90), 1,
      sym_element_node_end,
    ACTIONS(143), 2,
      sym_comment,
      sym_text_node,
    STATE(30), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [946] = 8,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(145), 1,
      sym__mustache_statement_start,
    STATE(23), 1,
      sym_element_node_start,
    STATE(29), 1,
      sym_block_statement_start,
    STATE(85), 1,
      sym_element_node_void,
    STATE(91), 1,
      sym_block_statement_end,
    ACTIONS(143), 2,
      sym_comment,
      sym_text_node,
    STATE(30), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [976] = 8,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(147), 1,
      sym__mustache_statement_start,
    STATE(23), 1,
      sym_element_node_start,
    STATE(29), 1,
      sym_block_statement_start,
    STATE(80), 1,
      sym_block_statement_end,
    STATE(85), 1,
      sym_element_node_void,
    ACTIONS(143), 2,
      sym_comment,
      sym_text_node,
    STATE(30), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [1006] = 8,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 1,
      anon_sym_LT,
    ACTIONS(157), 1,
      sym__mustache_statement_start,
    STATE(22), 1,
      sym_element_node_start,
    STATE(31), 1,
      sym_block_statement_start,
    STATE(73), 1,
      sym_element_node_void,
    ACTIONS(151), 2,
      sym_comment,
      sym_text_node,
    STATE(28), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [1036] = 8,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(145), 1,
      sym__mustache_statement_start,
    STATE(23), 1,
      sym_element_node_start,
    STATE(29), 1,
      sym_block_statement_start,
    STATE(84), 1,
      sym_block_statement_end,
    STATE(85), 1,
      sym_element_node_void,
    ACTIONS(160), 2,
      sym_comment,
      sym_text_node,
    STATE(26), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [1066] = 8,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_LT_SLASH,
    ACTIONS(170), 1,
      sym__mustache_statement_start,
    STATE(23), 1,
      sym_element_node_start,
    STATE(29), 1,
      sym_block_statement_start,
    STATE(85), 1,
      sym_element_node_void,
    ACTIONS(162), 2,
      sym_comment,
      sym_text_node,
    STATE(30), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [1096] = 8,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(147), 1,
      sym__mustache_statement_start,
    STATE(23), 1,
      sym_element_node_start,
    STATE(29), 1,
      sym_block_statement_start,
    STATE(85), 1,
      sym_element_node_void,
    STATE(92), 1,
      sym_block_statement_end,
    ACTIONS(173), 2,
      sym_comment,
      sym_text_node,
    STATE(27), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [1126] = 8,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      sym__mustache_statement_start,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym_element_node_start,
    STATE(31), 1,
      sym_block_statement_start,
    STATE(73), 1,
      sym_element_node_void,
    ACTIONS(177), 2,
      sym_comment,
      sym_text_node,
    STATE(28), 5,
      sym__declaration,
      sym_element_node,
      sym_mustache_statement,
      sym_block_statement,
      aux_sym_template_repeat1,
  [1156] = 3,
    ACTIONS(183), 1,
      anon_sym_DOT,
    ACTIONS(179), 4,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
    ACTIONS(181), 6,
      anon_sym_as,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1174] = 3,
    ACTIONS(185), 1,
      anon_sym_DOT,
    ACTIONS(179), 5,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(181), 5,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1192] = 2,
    ACTIONS(187), 4,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
    ACTIONS(189), 6,
      anon_sym_as,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1207] = 2,
    ACTIONS(191), 5,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(193), 5,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1222] = 2,
    ACTIONS(195), 4,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
    ACTIONS(197), 6,
      anon_sym_as,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1237] = 2,
    ACTIONS(199), 5,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(201), 5,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1252] = 2,
    ACTIONS(191), 4,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
    ACTIONS(193), 6,
      anon_sym_as,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1267] = 2,
    ACTIONS(203), 5,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(205), 5,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1282] = 8,
    ACTIONS(35), 1,
      anon_sym_as,
    ACTIONS(207), 1,
      anon_sym_GT,
    ACTIONS(209), 1,
      anon_sym_SLASH_GT,
    ACTIONS(211), 1,
      sym_attribute_name,
    ACTIONS(213), 1,
      sym__mustache_statement_start,
    ACTIONS(215), 1,
      sym_comment,
    STATE(118), 1,
      sym_block_params,
    STATE(51), 3,
      sym_attribute_node,
      sym_mustache_statement,
      aux_sym_element_node_start_repeat1,
  [1309] = 8,
    ACTIONS(35), 1,
      anon_sym_as,
    ACTIONS(207), 1,
      anon_sym_GT,
    ACTIONS(211), 1,
      sym_attribute_name,
    ACTIONS(213), 1,
      sym__mustache_statement_start,
    ACTIONS(215), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_SLASH_GT,
    STATE(118), 1,
      sym_block_params,
    STATE(51), 3,
      sym_attribute_node,
      sym_mustache_statement,
      aux_sym_element_node_start_repeat1,
  [1336] = 2,
    ACTIONS(219), 4,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
    ACTIONS(221), 6,
      anon_sym_as,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1351] = 2,
    ACTIONS(199), 4,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
    ACTIONS(201), 6,
      anon_sym_as,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1366] = 2,
    ACTIONS(203), 4,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
    ACTIONS(205), 6,
      anon_sym_as,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1381] = 2,
    ACTIONS(219), 5,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(221), 5,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1396] = 2,
    ACTIONS(223), 4,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
    ACTIONS(225), 6,
      anon_sym_as,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1411] = 2,
    ACTIONS(223), 5,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(225), 5,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1426] = 2,
    ACTIONS(195), 5,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(197), 5,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1441] = 2,
    ACTIONS(187), 5,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym__mustache_statement_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(189), 5,
      sym_identifier,
      sym_helper_identifier,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
  [1456] = 7,
    ACTIONS(35), 1,
      anon_sym_as,
    ACTIONS(211), 1,
      sym_attribute_name,
    ACTIONS(213), 1,
      sym__mustache_statement_start,
    ACTIONS(227), 1,
      anon_sym_GT,
    ACTIONS(229), 1,
      sym_comment,
    STATE(112), 1,
      sym_block_params,
    STATE(52), 3,
      sym_attribute_node,
      sym_mustache_statement,
      aux_sym_element_node_start_repeat1,
  [1480] = 6,
    ACTIONS(231), 1,
      anon_sym_GT,
    ACTIONS(233), 1,
      sym_attribute_name,
    ACTIONS(236), 1,
      anon_sym_as,
    ACTIONS(238), 1,
      sym__mustache_statement_start,
    ACTIONS(241), 1,
      sym_comment,
    STATE(52), 3,
      sym_attribute_node,
      sym_mustache_statement,
      aux_sym_element_node_start_repeat1,
  [1501] = 6,
    ACTIONS(213), 1,
      sym__mustache_statement_start,
    ACTIONS(244), 1,
      anon_sym_SQUOTE,
    ACTIONS(246), 1,
      anon_sym_DQUOTE,
    ACTIONS(248), 1,
      sym_number_literal,
    STATE(62), 2,
      sym_concat_statement,
      sym_mustache_statement,
    STATE(63), 2,
      sym__single_quote_concat_statement,
      sym__double_quote_concat_statement,
  [1522] = 4,
    ACTIONS(250), 1,
      anon_sym_PIPE,
    STATE(97), 1,
      sym__identifier,
    ACTIONS(252), 2,
      sym_identifier,
      sym_helper_identifier,
    STATE(55), 2,
      sym_path_expression,
      aux_sym_block_params_repeat1,
  [1537] = 4,
    ACTIONS(254), 1,
      anon_sym_PIPE,
    STATE(97), 1,
      sym__identifier,
    ACTIONS(252), 2,
      sym_identifier,
      sym_helper_identifier,
    STATE(57), 2,
      sym_path_expression,
      aux_sym_block_params_repeat1,
  [1552] = 3,
    ACTIONS(260), 1,
      anon_sym_EQ,
    ACTIONS(258), 2,
      sym_attribute_name,
      anon_sym_as,
    ACTIONS(256), 3,
      sym_comment,
      anon_sym_GT,
      sym__mustache_statement_start,
  [1565] = 4,
    ACTIONS(262), 1,
      anon_sym_PIPE,
    STATE(97), 1,
      sym__identifier,
    ACTIONS(264), 2,
      sym_identifier,
      sym_helper_identifier,
    STATE(57), 2,
      sym_path_expression,
      aux_sym_block_params_repeat1,
  [1580] = 2,
    ACTIONS(267), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(269), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1590] = 2,
    ACTIONS(273), 2,
      sym_attribute_name,
      anon_sym_as,
    ACTIONS(271), 3,
      sym_comment,
      anon_sym_GT,
      sym__mustache_statement_start,
  [1600] = 4,
    ACTIONS(275), 1,
      anon_sym_SQUOTE,
    ACTIONS(277), 1,
      sym__mustache_safe_single_quote_string_literal_content,
    ACTIONS(279), 1,
      sym__mustache_statement_start,
    STATE(70), 2,
      sym_mustache_statement,
      aux_sym__single_quote_concat_statement_repeat1,
  [1614] = 4,
    ACTIONS(281), 1,
      anon_sym_DQUOTE,
    ACTIONS(283), 1,
      sym__mustache_safe_double_quote_string_literal_content,
    ACTIONS(285), 1,
      sym__mustache_statement_start,
    STATE(72), 2,
      sym_mustache_statement,
      aux_sym__double_quote_concat_statement_repeat1,
  [1628] = 2,
    ACTIONS(289), 2,
      sym_attribute_name,
      anon_sym_as,
    ACTIONS(287), 3,
      sym_comment,
      anon_sym_GT,
      sym__mustache_statement_start,
  [1638] = 2,
    ACTIONS(293), 2,
      sym_attribute_name,
      anon_sym_as,
    ACTIONS(291), 3,
      sym_comment,
      anon_sym_GT,
      sym__mustache_statement_start,
  [1648] = 2,
    ACTIONS(295), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(297), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1658] = 2,
    ACTIONS(301), 2,
      sym_attribute_name,
      anon_sym_as,
    ACTIONS(299), 3,
      sym_comment,
      anon_sym_GT,
      sym__mustache_statement_start,
  [1668] = 2,
    ACTIONS(303), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(305), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1678] = 2,
    ACTIONS(307), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(309), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1688] = 2,
    ACTIONS(297), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(295), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1698] = 2,
    ACTIONS(313), 2,
      sym_attribute_name,
      anon_sym_as,
    ACTIONS(311), 3,
      sym_comment,
      anon_sym_GT,
      sym__mustache_statement_start,
  [1708] = 4,
    ACTIONS(279), 1,
      sym__mustache_statement_start,
    ACTIONS(315), 1,
      anon_sym_SQUOTE,
    ACTIONS(317), 1,
      sym__mustache_safe_single_quote_string_literal_content,
    STATE(75), 2,
      sym_mustache_statement,
      aux_sym__single_quote_concat_statement_repeat1,
  [1722] = 4,
    ACTIONS(319), 1,
      anon_sym_DQUOTE,
    ACTIONS(321), 1,
      sym__mustache_safe_double_quote_string_literal_content,
    ACTIONS(324), 1,
      sym__mustache_statement_start,
    STATE(71), 2,
      sym_mustache_statement,
      aux_sym__double_quote_concat_statement_repeat1,
  [1736] = 4,
    ACTIONS(285), 1,
      sym__mustache_statement_start,
    ACTIONS(327), 1,
      anon_sym_DQUOTE,
    ACTIONS(329), 1,
      sym__mustache_safe_double_quote_string_literal_content,
    STATE(71), 2,
      sym_mustache_statement,
      aux_sym__double_quote_concat_statement_repeat1,
  [1750] = 2,
    ACTIONS(333), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(331), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1760] = 2,
    ACTIONS(337), 2,
      sym_attribute_name,
      anon_sym_as,
    ACTIONS(335), 3,
      sym_comment,
      anon_sym_GT,
      sym__mustache_statement_start,
  [1770] = 4,
    ACTIONS(339), 1,
      anon_sym_SQUOTE,
    ACTIONS(341), 1,
      sym__mustache_safe_single_quote_string_literal_content,
    ACTIONS(344), 1,
      sym__mustache_statement_start,
    STATE(75), 2,
      sym_mustache_statement,
      aux_sym__single_quote_concat_statement_repeat1,
  [1784] = 2,
    ACTIONS(349), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(347), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1794] = 2,
    ACTIONS(353), 2,
      sym_attribute_name,
      anon_sym_as,
    ACTIONS(351), 3,
      sym_comment,
      anon_sym_GT,
      sym__mustache_statement_start,
  [1804] = 2,
    ACTIONS(309), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(307), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1814] = 2,
    ACTIONS(351), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(353), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1824] = 2,
    ACTIONS(357), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(355), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1834] = 2,
    ACTIONS(361), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(359), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1844] = 2,
    ACTIONS(301), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(299), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1854] = 2,
    ACTIONS(347), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(349), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1864] = 2,
    ACTIONS(363), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(365), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1874] = 2,
    ACTIONS(331), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(333), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1884] = 2,
    ACTIONS(367), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(369), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1894] = 2,
    ACTIONS(369), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(367), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1904] = 2,
    ACTIONS(299), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(301), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1914] = 2,
    ACTIONS(371), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(373), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1924] = 2,
    ACTIONS(359), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(361), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1934] = 2,
    ACTIONS(355), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(357), 3,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym__mustache_statement_start,
  [1944] = 2,
    ACTIONS(365), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(363), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1954] = 2,
    ACTIONS(377), 2,
      sym_attribute_name,
      anon_sym_as,
    ACTIONS(375), 3,
      sym_comment,
      anon_sym_GT,
      sym__mustache_statement_start,
  [1964] = 2,
    ACTIONS(353), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
    ACTIONS(351), 3,
      sym_comment,
      ts_builtin_sym_end,
      sym_text_node,
  [1974] = 2,
    ACTIONS(379), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(381), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
  [1983] = 2,
    ACTIONS(383), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(385), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
  [1992] = 3,
    ACTIONS(179), 1,
      anon_sym_PIPE,
    ACTIONS(387), 1,
      anon_sym_DOT,
    ACTIONS(181), 2,
      sym_identifier,
      sym_helper_identifier,
  [2003] = 2,
    ACTIONS(389), 2,
      sym_comment,
      sym_text_node,
    ACTIONS(391), 2,
      anon_sym_LT,
      sym__mustache_statement_start,
  [2012] = 2,
    ACTIONS(299), 1,
      sym__mustache_safe_double_quote_string_literal_content,
    ACTIONS(301), 2,
      anon_sym_DQUOTE,
      sym__mustache_statement_start,
  [2020] = 2,
    STATE(48), 1,
      sym__identifier,
    ACTIONS(393), 2,
      sym_identifier,
      sym_helper_identifier,
  [2028] = 2,
    STATE(47), 1,
      sym__identifier,
    ACTIONS(395), 2,
      sym_identifier,
      sym_helper_identifier,
  [2036] = 2,
    STATE(103), 1,
      sym__identifier,
    ACTIONS(397), 2,
      sym_identifier,
      sym_helper_identifier,
  [2044] = 2,
    ACTIONS(223), 1,
      anon_sym_PIPE,
    ACTIONS(225), 2,
      sym_identifier,
      sym_helper_identifier,
  [2052] = 2,
    ACTIONS(351), 1,
      sym__mustache_safe_single_quote_string_literal_content,
    ACTIONS(353), 2,
      anon_sym_SQUOTE,
      sym__mustache_statement_start,
  [2060] = 2,
    ACTIONS(299), 1,
      sym__mustache_safe_single_quote_string_literal_content,
    ACTIONS(301), 2,
      anon_sym_SQUOTE,
      sym__mustache_statement_start,
  [2068] = 2,
    ACTIONS(351), 1,
      sym__mustache_safe_double_quote_string_literal_content,
    ACTIONS(353), 2,
      anon_sym_DQUOTE,
      sym__mustache_statement_start,
  [2076] = 1,
    ACTIONS(399), 2,
      anon_sym_GT,
      sym__mustache_statement_end,
  [2081] = 1,
    ACTIONS(401), 2,
      anon_sym_GT,
      sym__mustache_statement_end,
  [2086] = 1,
    ACTIONS(403), 1,
      anon_sym_GT,
  [2090] = 1,
    ACTIONS(405), 1,
      anon_sym_GT,
  [2094] = 1,
    ACTIONS(407), 1,
      sym_tag_name,
  [2098] = 1,
    ACTIONS(409), 1,
      anon_sym_GT,
  [2102] = 1,
    ACTIONS(411), 1,
      sym_identifier,
  [2106] = 1,
    ACTIONS(413), 1,
      sym__mustache_statement_end,
  [2110] = 1,
    ACTIONS(415), 1,
      sym__mustache_statement_end,
  [2114] = 1,
    ACTIONS(417), 1,
      anon_sym_DQUOTE,
  [2118] = 1,
    ACTIONS(419), 1,
      anon_sym_SQUOTE,
  [2122] = 1,
    ACTIONS(227), 1,
      anon_sym_GT,
  [2126] = 1,
    ACTIONS(421), 1,
      anon_sym_SQUOTE,
  [2130] = 1,
    ACTIONS(423), 1,
      anon_sym_DQUOTE,
  [2134] = 1,
    ACTIONS(425), 1,
      anon_sym_PIPE,
  [2138] = 1,
    ACTIONS(37), 1,
      sym__mustache_statement_end,
  [2142] = 1,
    ACTIONS(427), 1,
      sym__mustache_statement_end,
  [2146] = 1,
    ACTIONS(429), 1,
      sym_tag_name,
  [2150] = 1,
    ACTIONS(431), 1,
      sym_identifier,
  [2154] = 1,
    ACTIONS(433), 1,
      aux_sym__double_quote_string_literal_token1,
  [2158] = 1,
    ACTIONS(435), 1,
      aux_sym__single_quote_string_literal_token1,
  [2162] = 1,
    ACTIONS(437), 1,
      sym_tag_name,
  [2166] = 1,
    ACTIONS(439), 1,
      aux_sym__single_quote_string_literal_token1,
  [2170] = 1,
    ACTIONS(441), 1,
      aux_sym__double_quote_string_literal_token1,
  [2174] = 1,
    ACTIONS(443), 1,
      sym_tag_name,
  [2178] = 1,
    ACTIONS(445), 1,
      sym_identifier,
  [2182] = 1,
    ACTIONS(447), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 222,
  [SMALL_STATE(8)] = 264,
  [SMALL_STATE(9)] = 304,
  [SMALL_STATE(10)] = 346,
  [SMALL_STATE(11)] = 385,
  [SMALL_STATE(12)] = 424,
  [SMALL_STATE(13)] = 463,
  [SMALL_STATE(14)] = 502,
  [SMALL_STATE(15)] = 541,
  [SMALL_STATE(16)] = 580,
  [SMALL_STATE(17)] = 619,
  [SMALL_STATE(18)] = 658,
  [SMALL_STATE(19)] = 697,
  [SMALL_STATE(20)] = 736,
  [SMALL_STATE(21)] = 775,
  [SMALL_STATE(22)] = 814,
  [SMALL_STATE(23)] = 847,
  [SMALL_STATE(24)] = 880,
  [SMALL_STATE(25)] = 913,
  [SMALL_STATE(26)] = 946,
  [SMALL_STATE(27)] = 976,
  [SMALL_STATE(28)] = 1006,
  [SMALL_STATE(29)] = 1036,
  [SMALL_STATE(30)] = 1066,
  [SMALL_STATE(31)] = 1096,
  [SMALL_STATE(32)] = 1126,
  [SMALL_STATE(33)] = 1156,
  [SMALL_STATE(34)] = 1174,
  [SMALL_STATE(35)] = 1192,
  [SMALL_STATE(36)] = 1207,
  [SMALL_STATE(37)] = 1222,
  [SMALL_STATE(38)] = 1237,
  [SMALL_STATE(39)] = 1252,
  [SMALL_STATE(40)] = 1267,
  [SMALL_STATE(41)] = 1282,
  [SMALL_STATE(42)] = 1309,
  [SMALL_STATE(43)] = 1336,
  [SMALL_STATE(44)] = 1351,
  [SMALL_STATE(45)] = 1366,
  [SMALL_STATE(46)] = 1381,
  [SMALL_STATE(47)] = 1396,
  [SMALL_STATE(48)] = 1411,
  [SMALL_STATE(49)] = 1426,
  [SMALL_STATE(50)] = 1441,
  [SMALL_STATE(51)] = 1456,
  [SMALL_STATE(52)] = 1480,
  [SMALL_STATE(53)] = 1501,
  [SMALL_STATE(54)] = 1522,
  [SMALL_STATE(55)] = 1537,
  [SMALL_STATE(56)] = 1552,
  [SMALL_STATE(57)] = 1565,
  [SMALL_STATE(58)] = 1580,
  [SMALL_STATE(59)] = 1590,
  [SMALL_STATE(60)] = 1600,
  [SMALL_STATE(61)] = 1614,
  [SMALL_STATE(62)] = 1628,
  [SMALL_STATE(63)] = 1638,
  [SMALL_STATE(64)] = 1648,
  [SMALL_STATE(65)] = 1658,
  [SMALL_STATE(66)] = 1668,
  [SMALL_STATE(67)] = 1678,
  [SMALL_STATE(68)] = 1688,
  [SMALL_STATE(69)] = 1698,
  [SMALL_STATE(70)] = 1708,
  [SMALL_STATE(71)] = 1722,
  [SMALL_STATE(72)] = 1736,
  [SMALL_STATE(73)] = 1750,
  [SMALL_STATE(74)] = 1760,
  [SMALL_STATE(75)] = 1770,
  [SMALL_STATE(76)] = 1784,
  [SMALL_STATE(77)] = 1794,
  [SMALL_STATE(78)] = 1804,
  [SMALL_STATE(79)] = 1814,
  [SMALL_STATE(80)] = 1824,
  [SMALL_STATE(81)] = 1834,
  [SMALL_STATE(82)] = 1844,
  [SMALL_STATE(83)] = 1854,
  [SMALL_STATE(84)] = 1864,
  [SMALL_STATE(85)] = 1874,
  [SMALL_STATE(86)] = 1884,
  [SMALL_STATE(87)] = 1894,
  [SMALL_STATE(88)] = 1904,
  [SMALL_STATE(89)] = 1914,
  [SMALL_STATE(90)] = 1924,
  [SMALL_STATE(91)] = 1934,
  [SMALL_STATE(92)] = 1944,
  [SMALL_STATE(93)] = 1954,
  [SMALL_STATE(94)] = 1964,
  [SMALL_STATE(95)] = 1974,
  [SMALL_STATE(96)] = 1983,
  [SMALL_STATE(97)] = 1992,
  [SMALL_STATE(98)] = 2003,
  [SMALL_STATE(99)] = 2012,
  [SMALL_STATE(100)] = 2020,
  [SMALL_STATE(101)] = 2028,
  [SMALL_STATE(102)] = 2036,
  [SMALL_STATE(103)] = 2044,
  [SMALL_STATE(104)] = 2052,
  [SMALL_STATE(105)] = 2060,
  [SMALL_STATE(106)] = 2068,
  [SMALL_STATE(107)] = 2076,
  [SMALL_STATE(108)] = 2081,
  [SMALL_STATE(109)] = 2086,
  [SMALL_STATE(110)] = 2090,
  [SMALL_STATE(111)] = 2094,
  [SMALL_STATE(112)] = 2098,
  [SMALL_STATE(113)] = 2102,
  [SMALL_STATE(114)] = 2106,
  [SMALL_STATE(115)] = 2110,
  [SMALL_STATE(116)] = 2114,
  [SMALL_STATE(117)] = 2118,
  [SMALL_STATE(118)] = 2122,
  [SMALL_STATE(119)] = 2126,
  [SMALL_STATE(120)] = 2130,
  [SMALL_STATE(121)] = 2134,
  [SMALL_STATE(122)] = 2138,
  [SMALL_STATE(123)] = 2142,
  [SMALL_STATE(124)] = 2146,
  [SMALL_STATE(125)] = 2150,
  [SMALL_STATE(126)] = 2154,
  [SMALL_STATE(127)] = 2158,
  [SMALL_STATE(128)] = 2162,
  [SMALL_STATE(129)] = 2166,
  [SMALL_STATE(130)] = 2170,
  [SMALL_STATE(131)] = 2174,
  [SMALL_STATE(132)] = 2178,
  [SMALL_STATE(133)] = 2182,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(127),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(126),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mustache_statement_repeat1, 2),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(34),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(14),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(8),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(46),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(129),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(130),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_mustache_statement_repeat1, 2),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(33),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(10),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(9),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mustache_statement_repeat1, 2), SHIFT_REPEAT(43),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(28),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(111),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(6),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(30),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(128),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(7),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_expression, 1),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path_expression, 1),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__double_quote_string_literal, 3),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__double_quote_string_literal, 3),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_expression, 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_expression, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_quote_string_literal, 3),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__single_quote_string_literal, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 1),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_expression, 3),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_expression, 3),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_expression, 3),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path_expression, 3),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_node_start_repeat1, 2),
  [233] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_node_start_repeat1, 2), SHIFT_REPEAT(56),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_element_node_start_repeat1, 2),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_node_start_repeat1, 2), SHIFT_REPEAT(21),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_node_start_repeat1, 2), SHIFT_REPEAT(52),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_node, 1),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_node, 1),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_params_repeat1, 2),
  [264] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_params_repeat1, 2), SHIFT_REPEAT(97),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_node_start, 5),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element_node_start, 5),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__double_quote_concat_statement, 2),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__double_quote_concat_statement, 2),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_node, 3),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_node, 3),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concat_statement, 1),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_concat_statement, 1),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement_end, 4, .production_id = 2),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement_end, 4, .production_id = 2),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mustache_statement, 3),
  [301] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mustache_statement, 3),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_node_start, 4),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element_node_start, 4),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_node_end, 3),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element_node_end, 3),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_quote_concat_statement, 2),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__single_quote_concat_statement, 2),
  [315] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [319] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__double_quote_concat_statement_repeat1, 2),
  [321] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__double_quote_concat_statement_repeat1, 2), SHIFT_REPEAT(71),
  [324] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__double_quote_concat_statement_repeat1, 2), SHIFT_REPEAT(13),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_node, 1),
  [333] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element_node, 1),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_quote_concat_statement, 3),
  [337] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__single_quote_concat_statement, 3),
  [339] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__single_quote_concat_statement_repeat1, 2),
  [341] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__single_quote_concat_statement_repeat1, 2), SHIFT_REPEAT(75),
  [344] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__single_quote_concat_statement_repeat1, 2), SHIFT_REPEAT(11),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_node, 2),
  [349] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element_node, 2),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mustache_statement, 2),
  [353] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mustache_statement, 2),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 3, .production_id = 1),
  [357] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 3, .production_id = 1),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_node, 3),
  [361] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element_node, 3),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 2),
  [365] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 2),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_node_void, 3),
  [369] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element_node_void, 3),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element_node_start, 3),
  [373] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element_node_start, 3),
  [375] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__double_quote_concat_statement, 3),
  [377] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__double_quote_concat_statement, 3),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement_start, 5, .production_id = 2),
  [381] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement_start, 5, .production_id = 2),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement_start, 6, .production_id = 2),
  [385] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement_start, 6, .production_id = 2),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement_start, 4, .production_id = 2),
  [391] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement_start, 4, .production_id = 2),
  [393] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [395] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [397] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [399] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_params, 4),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_params, 3),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [411] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [441] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [447] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_glimmer_external_scanner_create(void);
void tree_sitter_glimmer_external_scanner_destroy(void *);
bool tree_sitter_glimmer_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_glimmer_external_scanner_serialize(void *, char *);
void tree_sitter_glimmer_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_glimmer(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_scanner = {
      (const bool *)ts_external_scanner_states,
      ts_external_scanner_symbol_map,
      tree_sitter_glimmer_external_scanner_create,
      tree_sitter_glimmer_external_scanner_destroy,
      tree_sitter_glimmer_external_scanner_scan,
      tree_sitter_glimmer_external_scanner_serialize,
      tree_sitter_glimmer_external_scanner_deserialize,
    },
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
